name: Commit, Tag, and Github Release

on:
  workflow_call:
    inputs:
      newVersion:
        required: true
        type: string
      dryRun:
        required: true
        type: boolean

jobs:
  extension:
    runs-on: ubuntu-latest

    steps:

      - id: checkout
        name: Checkout content repository
        uses: actions/checkout@v4

      - id: download-artifacts
        name: Download extension artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension-artifacts
          path: docs/

      - id: print-artifacts
        name: Print extension artifacts
        run: |
          ls -la docs/

      - id: commit-and-tag
        name: Commit changed files, add the release .crx to Github Pages
        if: ${{ inputs.dryRun == false }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "Version Update to ${{ inputs.newVersion }}"
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: github-actions
          add: |
            manifest.json 
            updates.xml
            docs/extension.crx
            docs/updates.xml
          push: true
          tag: ${{ inputs.newVersion }}
          pathspec_error_handling: exitImmediately

      - id: github-release
        name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: ${{ inputs.dryRun == false }}
        with:
          files: |
            docs/extension.crx.zip
          name: ${{ inputs.newVersion }}
          draft: false
          tag_name: ${{ inputs.newVersion }}